# Generated by Django 2.2.9 on 2020-07-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtcs',
            new_name='Products',
        ),
    ]
